package coordinator

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/homiakus/agctl/internal/engineering"
	harnessmodel "github.com/homiakus/agctl/internal/harness/model"
	"github.com/homiakus/agctl/internal/harness/task"
)

var (
	// ErrUnauthorizedRole indicates an unauthorized role attempted to exercise coordinator authority.
	ErrUnauthorizedRole = errors.New("unauthorized role for commit coordinator: only coordinator role is permitted")
	// ErrPlanDrift indicates the candidate was generated against a stale living plan.
	ErrPlanDrift = errors.New("living plan drift detected before commit coordination")
	// ErrInvalidCandidate indicates the candidate request is missing required fields.
	ErrInvalidCandidate = errors.New("invalid candidate commit request")
	// ErrPathEscape indicates a modified file path attempts to escape the target workspace root.
	ErrPathEscape = errors.New("file path escape violation")
	// ErrMissingIsolationRoot indicates the candidate isolation root does not exist.
	ErrMissingIsolationRoot = errors.New("missing or nonexistent isolation root")
)

// CandidateCommit encapsulates candidate changes generated by an isolated worker task.
type CandidateCommit struct {
	TaskID        string           `json:"taskId"`
	AttemptID     string           `json:"attemptId"`
	Role          engineering.Role `json:"role"`
	PlanDigest    string           `json:"planDigest"`
	TargetRoot    string           `json:"targetRoot"`
	IsolationRoot string           `json:"isolationRoot"`
	ModifiedFiles []string         `json:"modifiedFiles"`
	CommitMessage string           `json:"commitMessage"`
	Author        string           `json:"author"`
}

// Validate checks the candidate commit fields.
func (c CandidateCommit) Validate() error {
	if strings.TrimSpace(c.TaskID) == "" {
		return fmt.Errorf("%w: taskId is required", ErrInvalidCandidate)
	}
	if strings.TrimSpace(c.TargetRoot) == "" {
		return fmt.Errorf("%w: targetRoot is required", ErrInvalidCandidate)
	}
	if strings.TrimSpace(c.IsolationRoot) == "" {
		return fmt.Errorf("%w: isolationRoot is required", ErrInvalidCandidate)
	}
	if len(c.ModifiedFiles) == 0 {
		return fmt.Errorf("%w: modifiedFiles cannot be empty", ErrInvalidCandidate)
	}
	if err := harnessmodel.ValidatePlanDigest(c.PlanDigest); err != nil {
		return fmt.Errorf("%w: invalid plan digest: %v", ErrInvalidCandidate, err)
	}
	return nil
}

// CommitResult records the verified and applied commit changes.
type CommitResult struct {
	Success       bool      `json:"success"`
	TaskID        string    `json:"taskId"`
	CommitMessage string    `json:"commitMessage"`
	AppliedFiles  []string  `json:"appliedFiles"`
	PlanDigest    string    `json:"planDigest"`
	CommittedAt   time.Time `json:"committedAt"`
	TreeDigest    string    `json:"treeDigest"`
}

// CommitCoordinator enforces coordinator-only authority, living-plan binding, and safe diff application.
type CommitCoordinator struct {
	Now func() time.Time
}

// NewCommitCoordinator creates a new fenced commit coordinator.
func NewCommitCoordinator(now func() time.Time) *CommitCoordinator {
	if now == nil {
		now = time.Now
	}
	return &CommitCoordinator{Now: now}
}

// ApplyAndVerify validates coordinator role authority, verifies living-plan freshness,
// checks file paths for escape safety, and applies candidate modifications to the target root.
func (cc *CommitCoordinator) ApplyAndVerify(ctx context.Context, req CandidateCommit, currentPlan []byte) (CommitResult, error) {
	if err := req.Validate(); err != nil {
		return CommitResult{}, err
	}

	// Invariant I-031 & I-032: Enforce typed coordinator-only authority.
	if !req.Role.AllowsCoordinatorAuthority() {
		return CommitResult{}, fmt.Errorf("%w: role=%s is not coordinator", ErrUnauthorizedRole, req.Role)
	}

	// Invariant I-001 & I-030: Verify cryptographic living-plan consistency.
	env := harnessmodel.TaskEnvelope{PlanDigest: req.PlanDigest}
	if err := task.CheckPlanDrift(env, currentPlan); err != nil {
		return CommitResult{}, fmt.Errorf("%w: %v", ErrPlanDrift, err)
	}

	// Verify isolation root existence
	isoInfo, err := os.Stat(req.IsolationRoot)
	if err != nil || !isoInfo.IsDir() {
		return CommitResult{}, fmt.Errorf("%w: %s", ErrMissingIsolationRoot, req.IsolationRoot)
	}

	absTarget, err := filepath.Abs(req.TargetRoot)
	if err != nil {
		return CommitResult{}, fmt.Errorf("resolve target root: %w", err)
	}

	absIso, err := filepath.Abs(req.IsolationRoot)
	if err != nil {
		return CommitResult{}, fmt.Errorf("resolve isolation root: %w", err)
	}

	// Verify all modified files are strictly inside TargetRoot and exist in IsolationRoot
	cleanFiles := make([]string, 0, len(req.ModifiedFiles))
	for _, f := range req.ModifiedFiles {
		clean := filepath.Clean(f)
		if strings.HasPrefix(f, "/") || strings.HasPrefix(f, "\\") || strings.HasPrefix(clean, "/") || strings.HasPrefix(clean, "\\") || filepath.IsAbs(f) || filepath.IsAbs(clean) || strings.HasPrefix(clean, "..") || clean == "." {
			return CommitResult{}, fmt.Errorf("%w: invalid relative path %q", ErrPathEscape, f)
		}

		targetPath := filepath.Join(absTarget, clean)
		rel, err := filepath.Rel(absTarget, targetPath)
		if err != nil || strings.HasPrefix(rel, "..") {
			return CommitResult{}, fmt.Errorf("%w: path %q escapes target root", ErrPathEscape, f)
		}

		srcPath := filepath.Join(absIso, clean)
		srcInfo, err := os.Stat(srcPath)
		if err != nil || srcInfo.IsDir() {
			return CommitResult{}, fmt.Errorf("modified file %q not found in isolation root: %w", clean, err)
		}

		cleanFiles = append(cleanFiles, clean)
	}

	// Sort file list for deterministic digest computation
	sort.Strings(cleanFiles)

	hasher := sha256.New()

	// Apply verified files atomically
	for _, clean := range cleanFiles {
		srcPath := filepath.Join(absIso, clean)
		dstPath := filepath.Join(absTarget, clean)

		if err := os.MkdirAll(filepath.Dir(dstPath), 0755); err != nil {
			return CommitResult{}, fmt.Errorf("create destination dir for %q: %w", clean, err)
		}

		content, err := os.ReadFile(srcPath)
		if err != nil {
			return CommitResult{}, fmt.Errorf("read source file %q: %w", clean, err)
		}

		if err := os.WriteFile(dstPath, content, 0644); err != nil {
			return CommitResult{}, fmt.Errorf("write destination file %q: %w", clean, err)
		}

		_, _ = io.WriteString(hasher, clean+":")
		hasher.Write(content)
		_, _ = io.WriteString(hasher, ";")
	}

	now := cc.Now().UTC()
	treeDigest := hex.EncodeToString(hasher.Sum(nil))

	return CommitResult{
		Success:       true,
		TaskID:        req.TaskID,
		CommitMessage: req.CommitMessage,
		AppliedFiles:  cleanFiles,
		PlanDigest:    req.PlanDigest,
		CommittedAt:   now,
		TreeDigest:    treeDigest,
	}, nil
}
